- hosts: local
   connection: local
      gather_facts: no
         tasks:
          - name: Create a new EC2 key         
              ec2_key:             
              name: nixcraft-key             
              region: us-west-1         
              register: ec2_key_result         
          - name: Save private key         
              copy: content="{{ ec2_key_result.key.private_key }}" dest="./aws.nixcraft.pem" mode=0600         
              when: ec2_key_result.changed