---
- hosts: localhost
  connection: local
  tasks:
  - name: Crear grupo de seguridad con HTTPS, HTTP y SSH
    ec2_group: 
      name: sg_profe
      vpc_id: vpc-7a117c07
      description: sg con las reglas
      region: us-west-1
      rules:
      # se cambio TCP por SSH que pide en la consigna 
        - proto: ssh 
          ports:
          - 443
          - 80
          #El puerto 23 es TCP
          - 22
          - 8080
          cidr_ip: 0.0.0.0/0
          rule_desc: Acepto todo el trafico
  - name: Creamos nuestro servidor
    ec2:
      region: us-east-1
      instance_type: t2.micro
      image: ami-0c02fb55956c7d316  
      instance_tags:
        Name: Instancia_Profe
      wait: yes
      wait_timeout: 500
      # se cambio el nombre al mismo que aparece en la linea 14
      group: sg_profe
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: subnet-82bceedd
      # se cambio la ip publica por yes 
      assign_public_ip: yes
      key_name: millave
    register: info
  - name: DNS Publico de nuestro servidor
    debug:
      msg: "La ip publica es {{ info.instances[0].public_ip }} y su DNS es {{ info.instances[0].public_dns_name }}"