# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
  config.vm.box = "ubuntu/focal64"
  #config.vm.boot_timeout = 900 # a mi me tiro algunos errores de timeout, asi que lo saque
  config.vm.synced_folder ".", "/vagrant", disabled: true
  server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
        # Customize the amount of memory and cpus on the VM:
      vb.memory = 2048
      vb.cpus = 2
    end
  server.vm.hostname = "server"
  server.vm.network "public_network"
  server.vm.provision "shell", inline: <<-SHELL #aca empieza a escribir comandos en el shell de la maquina virtual
      sudo apt-get update
      sudo apt-get install -y python3 #Instala python3 chequear con "python3 --version"
      sudo apt-get install -y unzip #Instala un descomprimidor de archivos zip, chequear con "unzip --version"
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" # curl navega a la pagina y -o es para cambiar el nombre del archivo de salida.
      unzip awscliv2.zip # descomprime el archivo
      sudo ./aws/install # supongo que instala aws o navega a una carpeta que se llama install
      sudo apt install software-properties-common -y #carga unos packetes que no tengo idea que hacen, en mi caso 0 upgraded
      sudo add-apt-repository --yes --update ppa:ansible/ansible #ni idea, supongo hace algo necesario para luego instalar ansible
      sudo apt install ansible -y #aca instala ansible en el doc dice que esto se debe instalar despues de python, pip y boto3?!
      sudo apt-get install python3-pip -y #el paquete de python PIP
      pip3 install boto3 #Instala boto3
      pip3 install boto # Instala otro boto, supongo que por si las moscas
      #Segun el doc estaria faltando instalar aws - sudo apt install awscli
      
      #---------HASTA ACA SEGUN EL DOC, LUEGO NO TENGO IDEA QUE HACE ---------
      #curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      #sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com/ $(lsb_release -cs) main"
      #sudo apt install terraform
      #sudo apt install net-tools
    SHELL
  end  
end
